# Generated by Django 5.1.7 on 2025-03-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('Single', 'Single Room'), ('Double', 'Double Room'), ('Shared', 'Shared Room')], default='Single', max_length=10),
        ),
        migrations.AddField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
